spin_manifest_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
name = "example-app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "example-app"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm install && npm run build"
