name: 'setup-spin'
description: 'downloads and add spin to your PATH'
author: 'Fermyon Engineering'
inputs:
  version:
    required: false
    description: 'version of spin to setup'
    default: 'v0.10.0'
  plugins:
    required: false
    description: 'comma separated list of plugins to install'
  build:
    required: false
    description: 'run spin build command'
  app_config_file:
    required: false
    description: 'path to spin.toml file'
  cloud_base_url:
    required: false
    description: 'cloud base url to use. defaults to https://cloud.fermyon.com'
  oci_app_reference:
    required: false
    description: 'OCI Registry reference. Learn more at https://developer.fermyon.com/spin/spin-oci'
  deploy:
    required: false
    description: 'deploys the app to Fermyon Cloud'
runs:
  using: 'node16'
  main: 'dist/index.js'
