name: 'Build and deploy Spin app to Fermyon Cloud'
description: 'Build and deploy Spin app to Fermyon Cloud'
author: 'Fermyon Engineering'
inputs:
  manifest_file:
    required: false
    description: 'path to spin.toml file'
    default: 'spin.toml'
  fermyon_token:
    required: false
    description: 'personal access token for Fermyon Cloud'
  key_values:
    required: false
    description: 'Pass a key/value (key=value) to all components of the application. You can specify multiple key_values by putting each key/value pair on its own line'
  run_build:
    required: false
    description: 'run `spin build` if enabled (default)'  
    default: true
  variables:
    required: false
    description: 'Pass a variable (variable=value) to all components of the application. You can specify multiple variables by putting each variable/value pair on its own line'
outputs:
  app_url:
    description: 'the URL of the deployed app'
runs:
  using: 'node16'
  main: '../../dist/spin/deploy/index.js'
