name: deploy spin app preview e2e tests
on:
  pull_request:
    branches: ["main"]
    types: ['opened', 'synchronize', 'reopened', 'closed']

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19
      
      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run package
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spin-actions
          path: dist/spin/preview/index.js

  deploy-preview-fermyon-cloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved Github action
        uses: actions/download-artifact@v3
        with:
          name: spin-actions
          path: dist/spin/preview/

      - name: setup spin
        uses: ./spin/setup/
        with:
          version: canary
          plugins: js2wasm
          github_token: ${{ github.token }}

      - name: build and deploy preview
        uses: ./spin/preview/
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          manifest_file: example-app/spin.toml
          undeploy: ${{ github.event.pull_request && github.event.action == 'closed' }}
